# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio
email: farcasmihai91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! My name is Mihai and I'm a web developer with knowledge of both frontend and backend technologies,
  specialising in JavaScript, TypeScript, NodeJS, HTML and CSS. 
  I am also an aspiring software architect, determined to learn more about NoSQL databases, Micro-Service architecture,
  Big Data and Machine Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: farcasmihai91
github_username:  farcasmihai91

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown
